### ISSUE TITLE
java.lang.NoClassDefFoundError on NativeInstantiationImpl without using OracleJdk

### ISSUE THREAD

**Issue by Onirik79** [astonbitecode/j4rs#24]
I'm using j4rs successfully in some testing code.

However, since I will need to use a different version of vm than oracle, I uninstalled OracleJdk version 8 and 9 (which I had on my windows 10 64 bit) and installed an openJdk 14.0.2.

At this point, after solving a path problem related to jvm.dll, I got this output by trying again to perform a test related to a static method call java.lang.System.currentTimeMillis (j4rs doc example)

/.cargo/bin/cargo.exe run --color=always --package java2rust --bin java2rust
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `target\debug\java2rust.exe`
            test_call_static_method:    308 microseconds
WARNING in native method: JNI call made with exception pending
WARNING in native method: JNI call made with exception pending
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: org/astonbitecode/j4rs/api/instantiation/NativeInstantiationImpl
Caused by: java.lang.ClassNotFoundException: org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JavaError("An Exception was thrown by Java while creating global ref... Please check the logs or the console.")', 

I don't think it's an OpenJdk configuration problem as the same test done using the jni-rs cargo works (but if you need more information about it I'm here).

Looking for a bit of how to solve the problem I ended up in this page that I think (but I don't know if) it can help:
https://developer.android.com/training/articles/perf-jni.html#exceptions

**Comment by Onirik79** [comment]
Sorry, I instantiated both the vm with jni.rs and j4rs in the same code, definitely an unwise thing.
I retried the test without jni-rs and j4rs also works with OpenJdk 14.0.2, so I don't know if the problem can be defined as such by now.

**Comment by astonbitecode** [comment]
Well, in this case, the classpath was not correctly set for the `j4rs` and this was your issue.

j4rs needs the `j4rs-0.12.0-jar-with-dependencies.jar` in the classpath in order to work. The problem was that this jar could not be found.

During rust build (and specifically, while the j4rs crate is being built), the jar is copied under a directory that is called `jassets`. The classpath needs to include this jar by default and j4rs implicitly does this while creating the JVM. However, the JVM apparently was already created and of course the classpath was not populated as should.

Generally, I assume that you want to run a Rust application that will create a JVM and call Java code (Rust -> Java direction). However, you showed that the command you are using is `java2rust`, which dictates the opposite direction (Java -> Rust). The two directions should be differently handled.

If you still have issues, please write some lines describing your use case and what you are trying to achieve, in order to be able to better help.

Thanks and good luck with your project!

BTW, make sure that you have your `JAVA_HOME` environmental variable pointing to the Java installation that you want to use. j4rs uses it to locate the `jvm.dll`.

**Comment by Onirik79** [comment]
Thank you for your answer. The problem is solved!

Oh! java2rust is just a random name given to the test project, it's semantically wrong, I'm using j4rs just like your assumption: Rust -> Java direction.

Although I am finding j4rs more usable and documented than jni-rs I have doubts about who is more performing and I am doing tests about it, probably in some time I will be able to give you some comparison results to think about.

**Comment by astonbitecode** [comment]
Yes, j4rs is created to provide several facilities to easier use Java from Rust (JVM setup without additional configuration like jvm.dll inclusion, easier Java invocations, classpath setup and artifacts download from Maven repositories, JavaFX support etc).

Generally, reflection is used in order to achieve many of the invocations, but depending on the use case, there are some things that could be done to improve performance. 

I hope that the crate meets your requirements and of course, you are welcome to share any thoughts or findings... Nothing is written on the stone and I believe there is always space for improvements.
